name: контейнер

on:
  push:
    branches: [main]
    paths:
      - .github/workflows/container.yml
      - .dockerignore
      - Dockerfile
      - CMakeLists.txt
      - include/**
      - src/**
      - tests/**
  workflow_dispatch:

permissions:
  contents: read
  packages: write

jobs:
  build-and-publish:
    name: Сборка и публикация
    runs-on: ubuntu-22.04
    steps:
      - name: Получение исходного кода
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd

      - name: Вход в GHCR
        uses: docker/login-action@4907a6ddec9925e35a0a9e82d7399ccc52663121
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Сборка и публикация
        uses: docker/build-push-action@f9f3042f7e2789586610d6e8b85c8f03e5195baf
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: |
            ghcr.io/nikkfh5/graph_nomemory:main
            ghcr.io/nikkfh5/graph_nomemory:sha-${{ github.sha }}
          labels: |
            org.opencontainers.image.source=${{ github.server_url }}/${{ github.repository }}
            org.opencontainers.image.revision=${{ github.sha }}
          build-args: |
            VCS_REF=${{ github.sha }}
